### ISSUE TITLE
when gamepad.mapping is "standard", id is discarded

### ISSUE THREAD

**Issue by gasp** [ensemblejs/gamepad-api-mappings#1]
When `window.navigator.getGamepads()[0].mapping === 'standard'`, the `mapping.json`file is discarded.

https://github.com/ensemblejs/gamepad-api-mappings/blob/master/src/get-mapping.js#L6

But, afaik, gamepad devices advertising themselves as "standard" do not respect the RFC as described in https://w3c.github.io/gamepad/#remapping

I would recommend parsing the mapping.json file, then defaulting to standard.

**Comment by distributedlife** [comment]
Fixed in 4.0.1.

Thanks.
